
import { Role } from '@prisma/client';

// This file is auto-generated by scripts/sync-frontend-permissions.js. Do not edit manually.

export const backendPermissionsMap = {
  "/billing/credit-notes": {
    "GET": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER"
    ],
    "POST": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "ACCOUNTANT"
    ]
  },
  "/billing/invoices": {
    "GET": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "ACCOUNTANT"
    ],
    "POST": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER"
    ]
  },
  "/billing/payments": {
    "GET": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "ACCOUNTANT"
    ],
    "POST": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "ACCOUNTANT"
    ]
  },
  "/billing/reconciliation": {
    "POST": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "ACCOUNTANT"
    ]
  },
  "/cash-register-sessions": {
    "POST": [
      "CASHIER",
      "MANAGER",
      "ADMIN",
      "SUPER_ADMIN"
    ]
  },
  "/cash-registers": {
    "GET": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "CASHIER"
    ],
    "POST": [
      "SUPER_ADMIN",
      "ADMIN"
    ]
  },
  "/cash-registers/[id]/close-session": {
    "POST": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "CASHIER"
    ]
  },
  "/cash-registers/[id]/movements": {
    "POST": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER"
    ]
  },
  "/inventory": {
    "GET": [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "WAREHOUSE"
    ]
  },
  "/inventory/adjust": {
    "POST": [
      "WAREHOUSE",
      "ADMIN",
      "SUPER_ADMIN",
      "MANAGER"
    ]
  },
  "/users": {
    "GET": [
      "SUPER_ADMIN",
      "ADMIN"
    ]
  }
};

export const canViewUsers = (role: Role) => backendPermissionsMap['/users']['GET'].includes(role);
export const canViewBilling = (role: Role) => backendPermissionsMap['/billing/invoices']['GET'].includes(role);
export const canViewWarehouse = (role: Role) => backendPermissionsMap['/inventory']['GET'].includes(role);
export const canViewCashRegisters = (role: Role) => backendPermissionsMap['/cash-registers']['GET'].includes(role);
export const canCreateInvoices = (role: Role) => backendPermissionsMap['/billing/invoices']['POST'].includes(role);
export const canManagePayments = (role: Role) => backendPermissionsMap['/billing/payments']['GET'].includes(role);
export const canManageCreditNotes = (role: Role) => backendPermissionsMap['/billing/credit-notes']['GET'].includes(role);
export const canViewReconciliation = (role: Role) => backendPermissionsMap['/billing/reconciliation']['POST'].includes(role);
export const canAddCashRegister = (role: Role) => backendPermissionsMap['/cash-registers']['POST'].includes(role);
export const canManageCashRegisterSession = (role: Role) => backendPermissionsMap['/cash-registers/[id]/close-session']['POST'].includes(role);
export const canCreateCashRegisterMovement = (role: Role) => backendPermissionsMap['/cash-registers/[id]/movements']['POST'].includes(role);
export const canManageWarehouse = (role: Role) => backendPermissionsMap['/inventory/adjust']['POST'].includes(role);
